backend/.gitignore, backend/README.md, backend/package-lock.json, backend/package.json, backend/src/App.js, backend/src/db/prisma/client.prisma.js, backend/src/db/prisma/schema.prisma, backend/src/middlewares/errorHandler.module.js, backend/src/modules/healthCheck.module.js, backend/src/modules/index.module.js, frontend/README.md, frontend/index.html, package.json
백엔드 프로젝트 초기화와 프론트엔드에서 간단한 주석 같은것만 조금 수정했습니다.
백엔드 프로젝트 초기화 방법은 backend 폴더로 들어가셔서 README.md 확인해보시면 어떻게 초기화했고 실행할 수 있는지 문서 정리해뒀어요
백엔드 한번 실행해보시고 문제가 없는 것 같다면 merge 부탁드립니당
백엔드 구성할때 수업시간에 사용한 환경과 거의 동일하게 맞춰서 다른 팀원분들도 무리없이 적용할 수 있을거라고 생각합니다.
프리즈마도 미리 설치해두었는데 render.com 에서 DB주소를 받아온 이후에 사용할 수 있어서 설치만되있고 실행은 아직 안돼요
=> feat: 백엔드 초기화 & 프론트엔드 단순 정리

frontend/src/App.jsx, frontend/src/layout/Header.jsx, frontend/src/pages/home/Home.jsx, frontend/src/pages/home/Home.module.css, frontend/vite.config.js
각 파일에 대한 절대 경로를 설정후 App.jsx 라우팅에 적용했습니다
=> [Feature/home] vite.config.js 절대경로 설정

frontend/src/components/TodayHabitCreate.jsx, frontend/src/components/TodayHabitCreate.module.css, frontend/src/pages/today-habit/TodayHabit.jsx, frontend/src/pages/today-habit/TodayHabit.module.css
=> feat: 습관페이지와 모달창 연결

frontend/src/pages/study-detail/HabitRecordTable.jsx, frontend/src/pages/study-detail/StudyContent.jsx, frontend/src/pages/study-detail/StudyContent.module.css, frontend/src/pages/study-detail/StudyDetail.jsx, frontend/src/pages/study-detail/StudyDetail.module.css, frontend/src/pages/study-detail/StudyDetailNav.jsx, frontend/src/pages/study-detail/StudyDetailNav.module.css
상세화면 레이아웃 프론트 작성하였습니다
세번째 컴포넌트 부분은 (grid 써서 구현해야함 )추후에 더 업데이트 하겠습니다
=> feat- 스터디 상세화면 레이아웃 

backend/.http, backend/src/modules/habitList.module.js, backend/src/modules/habits.module.js, backend/src/modules/index.module.js
1. habit router 추가
2. habitlist router 추가
3. index.module.js 에 두 라우터 추가
4. 각 라우터 get method 추가
Closes #39
=> feat: habits, habitlist 라우터 추가 및 get method 추가

backend/src/modules/index.module.js, backend/src/modules/study/getStudy.module.js
스터디 목록 조회 API를 개선하여 **검색, 정렬, 페이지네이션** 기능을 구현했습니다.  
사용자가 원하는 조건에 맞게 스터디를 쉽게 찾고 정렬할 수 있도록 했습니다.
---
- 스터디 목록 조회 API 구현
- **검색 기능** (제목, 설명)
- **정렬 기능** (포인트, 생성일자 기준)
- **페이지네이션** 기능 구현
---
- 제목과 설명 필드를 대상으로 검색
- **대소문자 구분 없이** 검색 가능
- `contains` 연산자 + `mode: 'insensitive'` 옵션 사용  
→ 부분 일치 및 대소문자 구분 없는 검색 지원
- **포인트 기준 정렬**: 오름차순(`asc`), 내림차순(`desc`)
- **생성일자 기준 정렬**: 최신순, 과거순
- `orderBy` 파라미터: 정렬 기준 (예: `point`, `createdAt`)
- `sort` 파라미터: 정렬 방향 (`asc` | `desc`)
- `offset`, `limit` 파라미터로 데이터 분할 조회
- 기본값: `offset=0`, `limit=10`
- 쿼리 파라미터는 자동 숫자 변환 처리
Closes #26
=> Feature/home-getStudyApi 스터디 조회 api 구현

frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/TodayFocus.module.css
현재 정빈님 부재시기도 하고, develop으로 merge 하려고 올리는 PR이니 바로 develop으로 PR 보냈습니다.
=> feat: 토스트 디자인 구현, 타이머 기능 구현 중

backend/src/db/prisma/schema.prisma
=> Feature/study edit update: 스키마 수정사항 반영

backend/package.json, frontend/.gitignore, frontend/src/api/axiosInstance.js, frontend/src/pages/home/BrowseCardList.jsx, frontend/src/server.js
- api base Url config 설정 
- 현재 배포 상태에 따른 base Url을 axiosInstance.js에서 vite의 개발 모드에 따라 구분하도록 구현
=> chore : Feature/chore api base Url config 설정 

backend/.http, backend/package-lock.json, backend/package.json, backend/src/modules/route/study.module.js, backend/src/modules/study/postStudy.module.js
- 스터디 만들기 post 기능 구현
- 비밀번호 암호화해서 저장 (bcrypt)
- 스터디 이름, 비밀번호 필수 입력
closes https://github.com/Jam1eL1/6-studyforest-phytoncide-FS/issues/35
=> feat : 스터디 만들기 BE기능 구현

frontend/package-lock.json, frontend/src/components/TodayHabitCreate.jsx, frontend/src/components/TodayHabitCreate.module.css
=> feat:습관모달오류수정 습관생성무한가능

backend/package.json, backend/src/db/prisma/migrations/20250330091605_250330_schema_update/migration.sql
=> feat: 스키마 마이그레이션 SQL 추가

backend/src/modules/study/studyGet.module.js, frontend/src/api/home/getStudy.api.js, frontend/src/pages/home/BrowseSection.jsx
Reverts Jam1eL1/6-studyforest-phytoncide-FS#96
=> Revert "fix : prisma 스키마 조회 에러 수정"

backend/src/modules/habitModules/habits.module.js, frontend/src/components/habitAPI.js
habit 생성과 삭제 
-백엔드 모듈 구현
-프론트엔드에서 가져오는 부분
구현했습니다.
=> feat: habitAPI connect create&delete

frontend/src/components/TodayHabitCreate.jsx
=> feat: 습관 모달 get 받아오기 연결

backend/src/modules/focusPointModules/focustPoint.module.js, backend/src/modules/route/focus.module.js, frontend/src/api/todayFocus/todayFocus.api.js, frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/TodayFocus.module.css, frontend/src/pages/today-focus/TodayFocusNavbar.jsx, frontend/src/pages/today-focus/TodayFocusPoint.jsx, frontend/src/pages/today-focus/TodayFocusTimer.jsx, frontend/src/pages/today-focus/TodayFocusTimerBtn.jsx, frontend/src/pages/today-focus/TodayFocusToast.jsx
=> feat: 타이머 기능 등등 구현

frontend/src/api/study/studyDelete.api.js, frontend/src/pages/study-detail/StudyContent.jsx, frontend/src/pages/study-detail/StudyDetail.jsx, frontend/src/pages/study-detail/StudyDetailNav.jsx
=> Feature/study 스터디 내용 정리

frontend/src/components/createStudyInput/Background.jsx, frontend/src/components/createStudyInput/Background.module.css, frontend/src/layout/Header.jsx, frontend/src/pages/study-detail/StudyDetailNav.jsx
- 헤더 스터디 만들기 주소 변경
- 스터디 만들기 이미지 사이즈 조절
=> fix : 주소 수정 및 css 이미지 사이즈 조절

backend/src/modules/focus/focustPoint.module.js, backend/src/modules/study/studyGet.module.js, frontend/src/api/study/studyDetail.api.js, frontend/src/api/todayFocus/todayFocus.api.js, frontend/src/pages/today-focus/TodayFocus.module.css, frontend/src/pages/today-focus/TodayFocusTimer.jsx, frontend/src/pages/today-focus/TodayFocusTimerBtn.jsx
스터디 상세보기 라우트 생성해두었고, API는 프론트엔드에 작성해두었습니다.
추가적인 디자인 관련해서 애니메이션 작업중입니다.
=> feat: 스터디 상세보기 API 생성, 오늘의 집중 다자인 애니메이션 추가

frontend/src/App.jsx, frontend/src/api/axiosInstance.js, frontend/src/api/home/getStudy.api.js, frontend/src/layout/Header.jsx, frontend/src/layout/Layout.jsx, frontend/src/pages/home/BrowseCardList.jsx, frontend/src/pages/home/BrowseSection.jsx, frontend/src/pages/home/Home.jsx, frontend/src/pages/home/RecentlySection.jsx, frontend/src/pages/home/SearchBar.jsx, frontend/src/pages/home/SortDropdown.jsx, frontend/src/utils/study.js
=> chore : prettier quoteStyle 설정 변경 ' ' -> " " 으로 변경

frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/TodayFocusPoint.jsx, frontend/src/pages/today-focus/TodayFocusTimer.jsx, frontend/src/pages/today-focus/TodayFocusTimer.module.css, frontend/src/pages/today-focus/TodayFocusTimerBtn.jsx, frontend/src/pages/today-focus/TodayFocusToast.jsx
타이머 클릭 시 전체선택 되어서 삭제 없이 바로 입력 가능하도록 구현했습니다. 타이머 클릭하게 되면 하이라이팅으로 선택 되었다는 사실을 알 수 있게 디자인 추가했습니다.
코드를 전체적으로 리팩터링 했습니다.
=> feat: 타이머 클릭 시 전체 선택 구현, 하이라이팅 디자인 추가 + 리팩터링

backend/package-lock.json, backend/package.json, frontend/src/pages/study-detail/study-emoji/StudyEmoji.jsx, frontend/src/pages/today-habit/HabitModal.module.css
=> feat:모달 css 반응형으로 구현 추가

backend/src/modules/edit-study-modules/studyUpdate.module.js, backend/src/modules/edit-study-modules/studyVerifyPassword.module.js, backend/src/modules/emoji/emojis.module.js, backend/src/modules/route/study.module.js, frontend/src/components/update-study-input/Background.jsx, frontend/src/components/update-study-input/Background.module.css, frontend/src/components/update-study-input/Description.module.css, frontend/src/components/update-study-input/DescriptionInput.jsx, frontend/src/components/update-study-input/Input.module.css, frontend/src/components/update-study-input/NicknameInput.jsx, frontend/src/components/update-study-input/PasswordCheck.jsx, frontend/src/components/update-study-input/PasswordInput.jsx, frontend/src/components/update-study-input/PasswordInput.module.css, frontend/src/components/update-study-input/StudyNameInput.jsx, frontend/src/pages/study-detail/StudyDetailNav.jsx, frontend/src/pages/study-detail/study-edit-form/StudyEditForm.jsx, frontend/src/pages/study-detail/study-edit-form/StudyEditForm.module.css, frontend/src/pages/study-detail/study-emoji/StudyEmoji.jsx, frontend/src/pages/study-detail/study-emoji/StudyEmoji.module.css
- 수정폼을 통해 DB까지 스터디 업데이트 정상작동합니다(이슈:스터디 수정시 bcrypt가 적용이 안되는 문제가 있어서 오늘 최신화 후에 다시 확인해볼 예정입니다)
- 스터디 상세화면에서 이모지 추가, 삭제가 가능합니다.(이슈:엄격모드로인해 컴포넌트가 2번씩 렌더링되어 디버깅시 이모지가 2배로 입력되는 이슈가있었는데 엄격모드 삭제후에는 아마 정상작동할것으로 예상됩니다. 그리고 세부 디자인이 조금 개선될 필요가 있으며 특히 모달 디자인이 많이 부족하여 다음 구현때는 모달 디자인을 집중적으로 개선할것으로 예상됩니다.)
=> feat: 수정폼 DB작업 OK & 스터디상세 이모지 OK

backend/src/modules/study/studyDelete.module.js, frontend/src/api/study/deleteStudy.api.js, frontend/src/components/delete-study-modal/DeleteStudyModal.jsx, frontend/src/components/delete-study-modal/DeleteStudyModal.module.css, frontend/src/components/delete-study-modal/DeleteStudyModalButton.jsx, frontend/src/components/delete-study-modal/DeleteStudyModalButton.module.css, frontend/src/components/delete-study-modal/DeleteStudyModalController.jsx, frontend/src/pages/study-detail/StudyContent.module.css, frontend/src/pages/study-detail/StudyDetailNav.jsx
- 스터디 삭제버튼을 누르면 비밀번호를 요구하고 데이터베이스에서 유저 정보와 일치하는지 검증, 그리고 삭제를 구현하여 유저를 홈화면으로 redirect 합니다.
- 유저의 localStorage에 있는 내용 또한 업데이트 하여 유저가 스터디 삭제 후 홈화면으로 이동되었을때, 최근 본 리스트에서 삭제된 스터디가 보이지 않습니다.
새로 만든 스터디 -> 지수의 테스트 1
삭제후 홈화면 최근 리스트
close #67
=> Feature/study delete 백엔드

backend/src/modules/route/habits.module.js, backend/src/modules/study/studyDelete.module.js, frontend/src/App.jsx, frontend/src/api/study/deleteStudy.api.js, frontend/src/components/delete-study-modal/DeleteStudyModal.jsx
기존에 삭제하기 있던 기능 백엔드 모듈을 팀내 미팅 후 정한 새로운 api 주소로 업데이트하여 적용시켰습니다.
=> Refactor: 스터디 삭제하기 모듈 api 엔드포인트 최신화에 따른 업데이트

frontend/src/App.jsx, frontend/src/api/home/getStudy.api.js, frontend/src/components/home/HomeCard.jsx, frontend/src/components/home/HomeCard.module.css
- Fix : 작성자명 넓이에 따라 포인트 컨테이너의 UI가 깨지는 문제 수정
- refactor : lazy loading 적용으로 초기 js 번들 최적화
=> Fix : 작성자명 넓이에 따라 포인트 컨테이너의 UI가 깨지는 문제 수정

frontend/src/layout/Header.jsx, frontend/src/pages/today-habit/TodayHabit.jsx
=> error: 경로오류 수정

backend/src/modules/habit/habits.module.js, frontend/src/api/today-habit/habit.api.js, frontend/src/layout/Header.jsx, frontend/src/pages/today-habit/HabitModal.jsx, frontend/src/pages/today-habit/HabitModal.module.css, frontend/src/pages/today-habit/Habits.jsx
put 으로 바꾸고 post, patch, delete는 삭제했습니다
=> fix : 라우터 경로와 API 수정

backend/src/modules/habit/habits.module.js, frontend/src/api/today-habit/habit.api.js, frontend/src/pages/study-detail/HabitRecordTable.jsx, frontend/src/pages/study-detail/StudyDetail.jsx
우선 습관기록표에 habit 타이틀만 불러오는 기능 적용하였습니다. 
- 스티커는 habit 의 완료여부에 따라 색깔이 적용될 예정입니다 (현재 구현 x)
- 스터디 상세내용 또한 아직 반영되지는 않음.
=> Feature - 스터디 상세화면에 habit 데이터 불러오기

frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/TodayFocusTimer.jsx
=> feat: 타이머 숫자 입력 기능 추가

frontend/src/components/home/HomeCard.jsx, frontend/src/components/home/HomeCard.module.css, frontend/src/layout/Header.jsx, frontend/src/layout/Header.module.css, frontend/src/pages/home/BrowseCardList.module.css, frontend/src/pages/home/BrowseSection.jsx, frontend/src/pages/home/BrowseSection.module.css, frontend/src/pages/home/Home.module.css, frontend/src/pages/home/RecentlySection.module.css, frontend/src/pages/home/SortDropdown.module.css
=> refactor : 피그마 디자인 시안과 다른점 피드백 후 수정

frontend/src/pages/today-habit/HabitModal.jsx, frontend/src/pages/today-habit/HabitModal.module.css
=> fix: 습관 모달 에러 수정

backend/src/modules/habit/habits.module.js
모달 반응형 css 수정 및
습관을 백에서 삭제하는 것이 아니라 isDone:true 으로 변경해서 남아있는 기록들이 지워지지 않도록 함
=> fix: 모달 반응형 css 수정 및 습관삭제가 아니라 isDone으로 변경

frontend/src/pages/today-habit/HabitModal.jsx, frontend/src/pages/today-habit/Habits.jsx, frontend/src/pages/today-habit/TodayHabit.jsx
모달 loading 추가해서 습관 수정 시 바로 반영 가능하도록 변경하였습니다.
=> Bugfix: 모달 loading 추가

frontend/public/images/icon/ic_plus.png:Zone.Identifier, frontend/src/pages/study-detail/study-emoji/StudyEmoji.jsx, frontend/src/pages/study-detail/study-emoji/StudyEmoji.module.css
=> feat: 이모지 및 모달디자인 개선

backend/src/modules/study/studyGet.module.js
- 최근 조회한 카드에서 이모지 안보이는 문제를 수정했습니다
=> fix : 최근 조회한 카드에서 이모지 안보이는 문제 수정

frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/TodayFocus.module.css, frontend/src/pages/today-focus/TodayFocusPoint.module.css, frontend/src/pages/today-focus/TodayFocusTimer.jsx
[fix: 포인트 기본 점수 변경(0 -> 3point)]
=> fix: 포인트 기본 점수 변경(0 -> 3point)

frontend/src/pages/today-habit/HabitModal.jsx, frontend/src/pages/today-habit/HabitModal.module.css
=> fix: 반응형 css적용

frontend/src/components/study-navbar/StudyNavbar.jsx, frontend/src/pages/today-focus/TodayFocusTimer.jsx
fix: StudyNavBar.jsx 홈 버튼 경로 스터디 상세로 수정
=> fix: StudyNavBar.jsx 홈 버튼 경로 스터디 상세로 수정

frontend/src/components/update-study-input/Input.module.css, frontend/src/pages/study-detail/study-emoji/StudyEmoji.jsx, frontend/src/pages/study-detail/study-emoji/StudyEmoji.module.css
- 이모지 모달 디자인과 이모지 피커 디자인을 세부적으로 개선
- 수정폼에서 Input.modules.css수정으로 폰트크기 조정
=> feat: 이모지 css 세부조정 & 수정폼 폰트크기 세부조정

backend/src/modules/habit/habitDone.module.js, frontend/src/api/today-habit/habit.api.js, frontend/src/api/today-habit/habitDone.api.js, frontend/src/pages/today-habit/CurrentTime.module.css, frontend/src/pages/today-habit/Habits.jsx, frontend/src/pages/today-habit/Habits.module.css
habit을 불러오고 따로 habitdone을 불러오는 것이 아니라 한꺼번에 불러오게 변경하면서 get habitdone api 삭제하였습니다.
=> Refactor: Feature/habit check

frontend/src/components/password-modal/PasswordModalButton.jsx
=> refactor: 불필요한 css module 제거

backend/src/modules/habit/habits.module.js, frontend/src/api/today-habit/habit.api.js, frontend/src/pages/today-habit/TodayHabit.jsx
=> fix: 주석지우고 habits모듈 가독성있게 정리

backend/src/modules/habit/habits.module.js, frontend/src/pages/today-habit/HabitModal.jsx
=> fix: 스키마 변경에 따른 네임 수정

frontend/src/App.jsx, frontend/src/api/focus/focusPoint.api.js, frontend/src/contexts/timerState.context.jsx, frontend/src/pages/today-focus/TodayFocus.jsx, frontend/src/pages/today-focus/components/Timer/TodayFocusTimer.jsx, frontend/src/pages/today-focus/components/Timer/TodayFocusTimerBtn.jsx, frontend/src/pages/today-focus/components/Toast/TodayFocusToast.jsx, frontend/src/utils/timerLogic.utils.js, frontend/vite.config.js
[refactor: 강사님 코드리뷰 최종 수정 - context API 적용]
=> refactor: 강사님 코드리뷰 최종 수정 - context API 적용

frontend/src/components/createStudyInput/StudyNameInput.jsx, frontend/src/components/update-study-input/NicknameInput.jsx, frontend/src/components/update-study-input/StudyNameInput.jsx
수정폼 닉네임&스터디이름 10글자제한 에러메시지 디자인 적용했습니다
=> feat: 수정폼 닉네임&스터디이름 10글자제한 에러메시지 디자인 적용

frontend/src/pages/home/HomeCard.module.css
=> feat : card 터치 애니메이션 모바일 환경에 맞춰 따로 설정
